#!/bin/bash
#
# kernel cleaner
# (dirtyepic@gentoo.org)

. /etc/init.d/functions.sh

if [[ ${EUID} != 0 ]]; then 
	eerror "Must be run as root"
	exit 1
fi

print_usage() {
    echo "Usage: $0 <kernel>"
	echo
	echo "  <kernel> can be a directory under /usr/src (eg. linux-2.6.39-gentoo-r4)"
	echo "  or a kernel name (eg. 2.6.39-gentoo-r4)."
    exit 1
}

# TODO - selective removal

while getopts "h" opt; do
	case ${opt} in
		h)	print_usage
			;;
		?)	print_usage
			;;
	esac
done

shift $(( ${OPTIND} - 1 ))

[[ -z ${1} ]] && print_usage

kername=${1/linux-/}
srcdir=linux-${kername}
pkgname=gentoo-sources:${kername/-gentoo/}

#echo "$srcdir"
#echo "$kername"
#echo "$pkgname"

# unmerge
if [[ $(qlist -I ${pkgname}) ]]; then
	einfo "Unmerging package ${pkgname}..."
	PORTAGE_ELOG_SYSTEM="" emerge -C --quiet "${pkgname}"
	if [[ $? != "0" ]]; then
		eerror "Unmerge failed"
		exit 1
	fi
else
	ewarn "Package ${pkgname} not installed, skipping unmerge"
fi

# remove leftovers
if [[ -d /usr/src/${srcdir} ]]; then
	echo
	einfo "Purging source directory /usr/src/${srcdir}..."
	rm -rf "/usr/src/${srcdir}"
	if [[ $? != "0" ]]; then
		eerror "Purging source failed"
		exit 1
	fi
fi

# Did we break /usr/src/linux
if [[ $(find -L /usr/src -name linux -type l) ]]; then
	einfo "Kernel symlink is broken.  Removing..."
	rm /usr/src/linux
	if [[ $? != "0" ]]; then
		eerror "Symlink removal failed"
		exit 1
	fi
	SYMWARN="true"
fi

# remove modules
if [[ -d /lib/modules/${kername} ]]; then 
	einfo "Purging /lib/modules/${kername}..."
	rm -rf "/lib/modules/${kername}"
	if [[ $? != "0" ]]; then
		eerror "Purging modules failed"
		exit 1
	fi
else
	ewarn "No modules found in /lib/modules/${kername}"
fi

# remove /boot stuff
for x in System.map config kernel; do
	if [[ -e /boot/${x}-${kername} ]]; then
		einfo "Removing /boot/${x}-${kername}..."
		rm -f "/boot/${x}-${kername}"
		if [[ $? != "0" ]]; then
			eerror "Removing /boot files failed"
			exit 1
		fi
	else
		einfo "${x}-${kername} not found"
	fi
done

echo
einfo "This script is currently too dumb to remove grub menu entries."
einfo "You'll have to do it yourself."
echo

if [[ ${SYMWARN} ]]; then
	ewarn "Purging this kernel broke the /usr/src/linux symlink."
	ewarn "You must restore it manually."
fi
